model:
  batch_size: 32
  embed_dim: 128
  num_epochs: 1
  kernel_size: 3
  num_heads: 4
  train_set_ratio: 0.7
  validation_set_ratio: 0.2

logging:
  level: "DEBUG"
  format: "[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s"