settings:
  batch_size: 32
  learning_rate: 0.001
  epochs: 50

environment:
  seed: 42
  device: "cuda" # Options: 'cuda', 'cpu'

logging:
  level: "DEBUG"
  format: "[%(asctime)s] [%(levelname)s] %(message)s"