model:
  batch_size: 32
  embed_dim: 128
  num_epochs: 1
  kernel_size: 3
  num_heads: 4
  train_set_ratio: 0.7
  validation_set_ratio: 0.2

logging:
  level: "INFO"
  format: "[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s"
  
reconstruction:
  frame_step: 2
  frames_max_threshold: 100
  tracked_objects: ('Car', 'Pedestrian')
  voxel_size: 0.05
  use_downsampling: False
  point_size: 3.0
  background_color: (0.2, 0.2, 0.2)